server:
  port: 8081

spring:
  datasource:
    driver-class-name: org.h2.Driver
    username: sa
    url: jdbc:h2:mem:desafio-transacao
    password:
  kafka:
    consumer:
      auto-offset-reset: latest
      group-id: transacoes-consumer
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
    topic: transacoes
    bootstrap-servers: ${KAFKA_HOST:localhost:9092}
  h2:
    console:
      enabled: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:18080/auth/realms/Proposta}
          jwk-set-uri: ${KEYCLOAK_JWKS_URI:http://localhost:18080/auth/realms/Proposta/protocol/openid-connect/certs}